Repository CEA-COSMIC/pysap-mri, pull requests merged in 2020-02, with the labels that each got.

#76 Fix Stack3D and also Smap estimation using stacks
  mri/operators/fourier/non_cartesian.py
  mri/reconstructors/utils/extract_sensitivity_maps.py
  mri/tests/test_fourier_adjoint.py
  mri/tests/test_reconstructors.py
Labels: In Progress, Testing, bug

#79 Extend SelfCalibrationReconstructor smaps use, add getter and setter
  mri/reconstructors/self_calibrating.py
Labels: In Progress, enhancement

#78 Add Gridsearch code scripts and remove old codes that are now invalid
  examples/gridsearch_launch.py
  mri/gridsearch.py
  mri/reconstructors/base.py
  mri/scripts/README.rst
  mri/scripts/__init__.py
  mri/scripts/gridsearch.conf
  mri/scripts/gridsearch.py
  mri/scripts/pysap_gridsearch
  mri/scripts/pysap_gridsearch_report
  mri/tests/test_scripts.py
Labels: In Progress, Testing, enhancement

#83 [SPLIT][SMALL] Fix cost to work more robustly for primal_dual optimization
  mri/optimizers/utils/cost.py
  mri/reconstructors/base.py
  mri/tests/test_reconstructors.py
Labels: enhancement
